version: "3"
services:
    mongo:
        image: mongo:5.0
        restart: always

    backend:
        image: ghcr.io/harvestcore/upgote:latest
        restart: always
        ports:
            - "8080:8080"
        environment:
            - MONGO_URI=mongodb://mongo:27017
        healthcheck:
            test: curl --fail -s http://localhost/api/healthcheck || exit 1
            interval: 30s
            timeout: 10s
            retries: 3
        depends_on:
            - mongo
