name: Build Docker images

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      name: ghcr.io/harvestcore/upgote

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: GitHub Registry - Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: GitHub Registry - Build images
        run: docker build . -f Dockerfile -t ${{ env.name }}

      - name: GitHub Registry - Tag images
        run: |
          docker tag ${{ env.name }} ${{ env.name }}:latest
          docker tag ${{ env.name }} ${{ env.name }}:${GITHUB_REF:10}
      - name: GitHub Registry - Push images
        run: |
          docker push ${{ env.name }}:latest
          docker push ${{ env.name }}:${GITHUB_REF:10}
