name: Tests

on:
  push:
    paths:
      - '.github/**'
      - 'api/**'
      - 'config/**'
      - 'core/**'
      - 'db/**'
      - 'log/**'
      - 'updater/**'
      - 'utils/**'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.17.12', '1.18.4']
    env:
      GOPATH: ${{ github.workspace }}
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}
    
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      with:
        path: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Run mongoDB
      uses: wbari/start-mongoDB@v0.2
      with:
        mongoDBVersion: 5.0

    - name: Create log file
      run: |
        sudo touch /var/log/upgote.log
        sudo chown runner:runner /var/log/upgote.log
        sudo chmod 0666 /var/log/upgote.log

    - name: Run tests
      run: make test
